services:
  virtualacademicadvisorwithrag:
    image: virtualacademicadvisorwithrag
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 APP\main.py "]
    ports:
      - 5678:5678
    environment:
      - COLBERT_GPU=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
